/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproject;
import java.awt.CardLayout;
/**
 *
 * @author Ivan
 */
public class MainMenu extends javax.swing.JFrame {
    private Login login;
    /**
     * Creates new form MainMenu
     */
    public MainMenu(Login login) {
        initComponents();
        setLocationRelativeTo(null);
        this.login = login;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdmitPatient = new javax.swing.JButton();
        btnCheckPatientRecord = new javax.swing.JButton();
        btnDischargePatient = new javax.swing.JButton();
        btnCheckPatientBalance = new javax.swing.JButton();
        btnSettlePatientBalance = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        pnlCardLayout = new javax.swing.JPanel();
        pnlAdmitPatient = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlCheckPatientRecord = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlDischargePatient = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlCheckPatientBalance = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlSettlePatientBalance = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");
        setPreferredSize(new java.awt.Dimension(750, 500));
        setSize(new java.awt.Dimension(500, 500));

        btnAdmitPatient.setText("Admit Patient");
        btnAdmitPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmitPatientActionPerformed(evt);
            }
        });

        btnCheckPatientRecord.setText("Check Patient's Record");
        btnCheckPatientRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckPatientRecordActionPerformed(evt);
            }
        });

        btnDischargePatient.setText("Discharge Patient ");
        btnDischargePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDischargePatientActionPerformed(evt);
            }
        });

        btnCheckPatientBalance.setText("Check Patient's Balance");
        btnCheckPatientBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckPatientBalanceActionPerformed(evt);
            }
        });

        btnSettlePatientBalance.setText("Settle Patient's Balance");
        btnSettlePatientBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettlePatientBalanceActionPerformed(evt);
            }
        });

        btnSignOut.setText("Sign out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignOut)
                    .addComponent(btnSettlePatientBalance)
                    .addComponent(btnCheckPatientBalance)
                    .addComponent(btnDischargePatient)
                    .addComponent(btnCheckPatientRecord)
                    .addComponent(btnAdmitPatient))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAdmitPatient)
                .addGap(18, 18, 18)
                .addComponent(btnCheckPatientRecord)
                .addGap(22, 22, 22)
                .addComponent(btnDischargePatient)
                .addGap(18, 18, 18)
                .addComponent(btnCheckPatientBalance)
                .addGap(18, 18, 18)
                .addComponent(btnSettlePatientBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignOut)
                .addGap(14, 14, 14))
        );

        pnlCardLayout.setLayout(new java.awt.CardLayout());

        jLabel5.setText("Admit Patient");

        javax.swing.GroupLayout pnlAdmitPatientLayout = new javax.swing.GroupLayout(pnlAdmitPatient);
        pnlAdmitPatient.setLayout(pnlAdmitPatientLayout);
        pnlAdmitPatientLayout.setHorizontalGroup(
            pnlAdmitPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdmitPatientLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel5)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        pnlAdmitPatientLayout.setVerticalGroup(
            pnlAdmitPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdmitPatientLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(458, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlAdmitPatient, "card6");

        jLabel1.setText("Check Patient's Record");

        javax.swing.GroupLayout pnlCheckPatientRecordLayout = new javax.swing.GroupLayout(pnlCheckPatientRecord);
        pnlCheckPatientRecord.setLayout(pnlCheckPatientRecordLayout);
        pnlCheckPatientRecordLayout.setHorizontalGroup(
            pnlCheckPatientRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckPatientRecordLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        pnlCheckPatientRecordLayout.setVerticalGroup(
            pnlCheckPatientRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckPatientRecordLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(450, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlCheckPatientRecord, "card2");

        jLabel2.setText("Discharge Patient");

        javax.swing.GroupLayout pnlDischargePatientLayout = new javax.swing.GroupLayout(pnlDischargePatient);
        pnlDischargePatient.setLayout(pnlDischargePatientLayout);
        pnlDischargePatientLayout.setHorizontalGroup(
            pnlDischargePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDischargePatientLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel2)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        pnlDischargePatientLayout.setVerticalGroup(
            pnlDischargePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDischargePatientLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(455, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlDischargePatient, "card3");

        jLabel3.setText("Check Patient's Balance");

        javax.swing.GroupLayout pnlCheckPatientBalanceLayout = new javax.swing.GroupLayout(pnlCheckPatientBalance);
        pnlCheckPatientBalance.setLayout(pnlCheckPatientBalanceLayout);
        pnlCheckPatientBalanceLayout.setHorizontalGroup(
            pnlCheckPatientBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckPatientBalanceLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel3)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        pnlCheckPatientBalanceLayout.setVerticalGroup(
            pnlCheckPatientBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckPatientBalanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlCheckPatientBalance, "card4");

        jLabel4.setText("Settle Patient's Balance");

        javax.swing.GroupLayout pnlSettlePatientBalanceLayout = new javax.swing.GroupLayout(pnlSettlePatientBalance);
        pnlSettlePatientBalance.setLayout(pnlSettlePatientBalanceLayout);
        pnlSettlePatientBalanceLayout.setHorizontalGroup(
            pnlSettlePatientBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettlePatientBalanceLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel4)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        pnlSettlePatientBalanceLayout.setVerticalGroup(
            pnlSettlePatientBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettlePatientBalanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlSettlePatientBalance, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnCheckPatientRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckPatientRecordActionPerformed

        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card2");
    }//GEN-LAST:event_btnCheckPatientRecordActionPerformed

    private void btnDischargePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDischargePatientActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card3");
    }//GEN-LAST:event_btnDischargePatientActionPerformed

    private void btnCheckPatientBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckPatientBalanceActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card4");
    }//GEN-LAST:event_btnCheckPatientBalanceActionPerformed

    private void btnSettlePatientBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettlePatientBalanceActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card5");
    }//GEN-LAST:event_btnSettlePatientBalanceActionPerformed

    private void btnAdmitPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmitPatientActionPerformed
        CardLayout cardLayout = (CardLayout) pnlCardLayout.getLayout();
        cardLayout.show(pnlCardLayout, "card6");
    }//GEN-LAST:event_btnAdmitPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmitPatient;
    private javax.swing.JButton btnCheckPatientBalance;
    private javax.swing.JButton btnCheckPatientRecord;
    private javax.swing.JButton btnDischargePatient;
    private javax.swing.JButton btnSettlePatientBalance;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlAdmitPatient;
    private javax.swing.JPanel pnlCardLayout;
    private javax.swing.JPanel pnlCheckPatientBalance;
    private javax.swing.JPanel pnlCheckPatientRecord;
    private javax.swing.JPanel pnlDischargePatient;
    private javax.swing.JPanel pnlSettlePatientBalance;
    // End of variables declaration//GEN-END:variables
}
